= Zápočtový program, Jazyk C# a platforma .NET + Pokročilé programování pro .NET I

Lukáš Jendele <lukas.jendele@gmail.com>, Ondrej Škopek <oskopek@matfyz.cz>

TODO ???FreeIDOS/PubTran++???

=== Stručne

INSERTNAMEHERE je ta navigačná aplikácia, ktorú ste vždy chceli mať:
ukaze Vam najrychlejsiu cestu tam, kam idete - bez nutnosti nekonecneho
nastovavania parametrov spojov a manualneho hladania na mape.

=== Podrobne

V zakladnej verzii je:

* Vyhladavanie najrychlejsich spojov z bodu do bodu,
nie zo zastavky (obcas je rychlejsie preist kusok peso)
** Zohladnovanie rychlosti chodze, ak mam zo sebou bicykel, taktiez.
* Preferencne kriteria: volba typu dopravneho prostriedku, preist cez dany bod,
optimalizacia vzdialenosti alebo casu, ...
* Funkcna navigacna aplikacia na Android/IOS (Praha + CR)
* Poskytnutie roznych variant ciest uzivatelovi (moze si vybrat)
* Modularny navrh: casti systemu by sa mali dat menit bez vacsich zmien aplikacie
(zmena poskytovatela mapovych/transportacnych dat, zmena vyhladavacieho algoritmu, ...)

=== Bonus

* Lokalizacia (CZ, SK, DE, default: EN)
* Zohladnovanie voci aktualnej premavke
* Paralelizacia algoritmu
